// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReserveMyRoom.API.Data;

#nullable disable

namespace ReserveMyRoom.API.Migrations
{
    [DbContext(typeof(ReserveMyRoomDbContext))]
    partial class ReserveMyRoomDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");
#pragma warning restore 612, 618
        }
    }
}
